apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentsetdemo
  labels:
    env: prod
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: mywebserver
          image: nginx:1.17.3
